[[Heptagon]]
arch = "aarch64"
git-tree-sha1 = "6f5b337c5a68f683ea4b5d87a0b18847c7a44cac"
os = "macos"

    [[Heptagon.download]]
    sha256 = "5dc280de9719bd489297a8b83441e3ecddd6c060059f3985aa844b65f351b5fd"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.4+0/Heptagon.v1.5.4.aarch64-apple-darwin.tar.gz"
[[Heptagon]]
arch = "aarch64"
git-tree-sha1 = "c37acbe28020acfe9bbba7e24ca375a23bbcf47f"
libc = "glibc"
os = "linux"

    [[Heptagon.download]]
    sha256 = "b26d80576300041e466d9c75431149b55c474957b1dbb1d8d61f738f6a61d557"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.4+0/Heptagon.v1.5.4.aarch64-linux-gnu.tar.gz"
[[Heptagon]]
arch = "aarch64"
git-tree-sha1 = "393870681683efd31a95803655fb37780de7ebc8"
libc = "musl"
os = "linux"

    [[Heptagon.download]]
    sha256 = "275a04d8593310bbc33d45aa153f153be9c36a77313cd7d04c79fda7ee91750b"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.4+0/Heptagon.v1.5.4.aarch64-linux-musl.tar.gz"
[[Heptagon]]
arch = "powerpc64le"
git-tree-sha1 = "c836dc77c82650b126e8e5443ddeb3676200666c"
libc = "glibc"
os = "linux"

    [[Heptagon.download]]
    sha256 = "ade567de94307ed465059842dd3162e0efd2098112341c892d6d3489f99e136a"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.4+0/Heptagon.v1.5.4.powerpc64le-linux-gnu.tar.gz"
[[Heptagon]]
arch = "riscv64"
git-tree-sha1 = "3e8d3569896fafbd4f413ffafb848beb5c2de7d5"
libc = "glibc"
os = "linux"

    [[Heptagon.download]]
    sha256 = "857db6c1bee99cbe0c92a2b295a3312cb662398a4b2b1c1f3391290d6b5d2b78"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.4+0/Heptagon.v1.5.4.riscv64-linux-gnu.tar.gz"
[[Heptagon]]
arch = "x86_64"
git-tree-sha1 = "5fbee1b6b6077f9bacec0dda7b10d3ddc2ff7672"
os = "macos"

    [[Heptagon.download]]
    sha256 = "af27d60bd99c184dca52f58e7e46961a27e1f9002e7a86995c1ecacfbbd39d55"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.4+0/Heptagon.v1.5.4.x86_64-apple-darwin.tar.gz"
[[Heptagon]]
arch = "x86_64"
git-tree-sha1 = "60cecbd8e3071e05d53bbd5acaf77de18ef0c53f"
libc = "glibc"
os = "linux"

    [[Heptagon.download]]
    sha256 = "e377ce0b68ca15b230a934ce586024aa23fd8f9ff54a31c30f8c2dc32c10110a"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.4+0/Heptagon.v1.5.4.x86_64-linux-gnu.tar.gz"
[[Heptagon]]
arch = "x86_64"
git-tree-sha1 = "6fbb3ea3ba84e167fc7f8daf3c9dbed31d6efd5d"
os = "windows"

    [[Heptagon.download]]
    sha256 = "07a2c0ae053ed5bcd00f9ce1bd3825651b972df3752bd30bf5a751c280449e48"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.4+0/Heptagon.v1.5.4.x86_64-w64-mingw32.tar.gz"
