[[Heptagon]]
arch = "aarch64"
git-tree-sha1 = "b0bbf4a27374e096de5e7cf302722c780a573b79"
os = "macos"

    [[Heptagon.download]]
    sha256 = "192cff61ba3a00998effb6283571229ae78d6d519bf1e7f167db990ced00f139"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.2+0/Heptagon.v1.5.2.aarch64-apple-darwin.tar.gz"
[[Heptagon]]
arch = "aarch64"
git-tree-sha1 = "3a0fdef8798973eeec66436eeedca03b2af8b565"
libc = "glibc"
os = "linux"

    [[Heptagon.download]]
    sha256 = "782fd740952fdf4d5916abdd31547b3ac0f1586aaf54d0bd39b64cab3ddea181"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.2+0/Heptagon.v1.5.2.aarch64-linux-gnu.tar.gz"
[[Heptagon]]
arch = "aarch64"
git-tree-sha1 = "9b38d26106b246c320c4d092e95ec6317ddc2f29"
libc = "musl"
os = "linux"

    [[Heptagon.download]]
    sha256 = "967771b933a101cad6f986a9138003e35ed5816fcd24564ae59060be96131b1b"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.2+0/Heptagon.v1.5.2.aarch64-linux-musl.tar.gz"
[[Heptagon]]
arch = "powerpc64le"
git-tree-sha1 = "a6f84179d50bec2d722f96b3c730f44527ff6c9e"
libc = "glibc"
os = "linux"

    [[Heptagon.download]]
    sha256 = "a8a74430ee6e92f7fbbaec47c07fc71cdfd218e53321bb54684239e439a28d0a"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.2+0/Heptagon.v1.5.2.powerpc64le-linux-gnu.tar.gz"
[[Heptagon]]
arch = "riscv64"
git-tree-sha1 = "2f36533ec0211b1c98b9364e0108e2781ba29fdd"
libc = "glibc"
os = "linux"

    [[Heptagon.download]]
    sha256 = "79015766e2cfde902df6dff4daa746a1ada9e6be9a1a95bfaf7a498c97df4608"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.2+0/Heptagon.v1.5.2.riscv64-linux-gnu.tar.gz"
[[Heptagon]]
arch = "x86_64"
git-tree-sha1 = "5de0c5d7dc8b4a35688c79289f4ea41dafe18e2d"
os = "macos"

    [[Heptagon.download]]
    sha256 = "ad19a6a3688b93f40775c927a412875e811ae0cc59f5bd6932b29627ea53b393"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.2+0/Heptagon.v1.5.2.x86_64-apple-darwin.tar.gz"
[[Heptagon]]
arch = "x86_64"
git-tree-sha1 = "da57af37c91adb11376bc3db7c77ced8c4bde970"
libc = "glibc"
os = "linux"

    [[Heptagon.download]]
    sha256 = "3cc94af10171f0901470805a941ea8e5f8c216076d9046d71f13e3a3c47beffa"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.2+0/Heptagon.v1.5.2.x86_64-linux-gnu.tar.gz"
[[Heptagon]]
arch = "x86_64"
git-tree-sha1 = "110ecee67c92397593eded563aed279b687234aa"
os = "windows"

    [[Heptagon.download]]
    sha256 = "e9d963eb71651d4244eb836f249a85174ac7f3dfb53c6ea45244230893c673aa"
    url = "https://github.com/JuliaBinaryWrappers/Heptagon_jll.jl/releases/download/Heptagon-v1.5.2+0/Heptagon.v1.5.2.x86_64-w64-mingw32.tar.gz"
